### ISSUE TITLE
[BUG] [QUESTION] Cannot read properties of undefined (reading 'args') - while accessing chromium.args

### ISSUE THREAD

**Issue by pratiksyngenta** [Sparticuz/chromium#16] opened 2022-11-12 11:10 UTC
## Environment
* `chromium` Version: "@sparticuz/chromium": "^106.0.2",
* `puppeteer` / `puppeteer-core` Version: "puppeteer-core": "18.0.5",
* Node.js Version: 16.X
* Lambda / GCF Runtime: 16.X

## Expected Behavior

should work pdf generation

## Current Behavior

Cannot read properties of undefined (reading 'args') - while accessing chromium.args

## Steps to Reproduce

https://88mgr9w8ec.execute-api.us-east-1.amazonaws.com/dev/graphql

```
mutation generatePDF {
  generatePDF
}
```

![image](https://user-images.githubusercontent.com/65348528/201471236-3b3c1166-84de-43ad-9318-ddf3b542e912.png)

```js
import fs from 'fs';
import path from 'path';
import puppeteer, { PDFOptions } from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
import handlebars from 'handlebars';

export const generatePDF = async (templateId: string, payload: object) => {
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });

  const templateHtml = fs.readFileSync(
    path.join(process.cwd(), `./apps/reports/src/utils/pdf-assets/templates/${templateId}.html`),
    'utf8',
  );
  const template = handlebars.compile(templateHtml);
  const html = template(payload);
  const page = await browser.newPage();
  await page.goto(`data:text/html;charset=UTF-8,${html}`, {
    waitUntil: 'networkidle0',
  });

  const pdfBuffer = await page.pdf(LAYOUT_CONFIG);
  return pdfBuffer;
};

const LAYOUT_CONFIG: PDFOptions = {
  width: '1230px',
  format: 'A4',
  headerTemplate: '<p></p>',
  footerTemplate: '<p></p>',
  displayHeaderFooter: false,
  margin: {
    top: '10px',
    bottom: '30px',
  },
  printBackground: true,
};

```

**Comment by Sparticuz** [comment] 2022-12-30 16:38
Are you using typescript or javascript? At this point, I've only got it running with CJS, not ESM. (Though the code is written in Typescript using ESM, it compiles down to CJS)

**Comment by Sparticuz** [comment] 2023-01-24 19:32
dupe of #31

**Closed by Sparticuz** 2023-01-24 19:32 UTC
Labels: bug
