### ISSUE TITLE
[REQUEST]I used layers and found that it takes 3.6 seconds to start Chromium on AWS Lambda. Is this normal, and is there any way to speed it up?

### ISSUE THREAD

**Issue by activeliang** [Sparticuz/chromium#131] opened 2023-08-03 10:34 UTC
As mentioned in the title, I'm wondering if it's possible to further improve the startup time of Chromium on AWS Lambda. I noticed that during "hot" loading, the startup time is only a fraction of a second, which indicates that the issue lies with the cold startup process.

**Comment by Sparticuz** [comment] 2024-04-03 16:53
dupe of #79

**Closed by Sparticuz** 2024-04-03 16:53 UTC
Labels: enhancement
