### ISSUE TITLE
navigation timeout

### ISSUE THREAD

**Issue by yspreen** [Sparticuz/chromium#87] opened 2023-04-16 01:18 UTC
running the same script locally and on a lambda gives me success when running my local chrome and a navigation timeout when running in the cloud

**Comment by yspreen** [comment] 2023-04-16 15:22
might've been a mistake on my end

**Comment by yspreen** [comment] 2023-04-29 18:55
I'm unable to fix this...  

```
    "@sparticuz/chromium": "^112.0.2",
    "aws-sdk": "^2.1048.0",
    "puppeteer-core": "^19.9.0"
```

**Comment by hasan-wajahat** [comment] 2023-05-04 16:20
What are the resources that you have assigned to lambda? Time out can actually be caused by factors outside of puppeteer itself and can have to do with the available resources.

**Comment by yspreen** [comment] 2023-05-06 23:26
unfortunately I can't post a code snippet bc the website I'm using is confidential. example.com works, a more complex site that uses canvas doesn't. resources are

  timeout     = 120
  memory_size = 1000

@Sparticuz @hasan-wajahat

**Comment by yspreen** [comment] 2023-05-06 23:27
i want to reiterate that I previously used https://github.com/alixaxel/chrome-aws-lambda without issues

**Comment by hasan-wajahat** [comment] 2023-05-08 06:21
@yspreen I believe your memory size is rather small.
Can you please share whether you get navigation errors all the time or occasionally?

I have also gotten occasional navigation errors after I migrated to this package and like you got none with Alixxael one. If that is the case for you as well then you are right. I along with couple of others have brought this issue as well but there hasn't been a resolution for it yet.

I believe @Sparticuz is of the opinion that its related to Chrome upgrading but I think there is more to it. And would love a solution as well.

If you are getting occasional timeouts then probably the only solution is to go back to the previous package (which is not an option for me.)

**Comment by Sparticuz** [comment] 2023-05-08 13:18
Canvas might uses opengl, so you'll need to make sure that the opengl drivers are working properly. I do test that they are working properly during testing, but different args and such can affect it.

**Comment by hasan-wajahat** [comment] 2023-05-09 05:14
@yspreen it should not fail every time. There is something wrong with either some argument on your end or some other env related thing.

**Comment by felipeclopes** [comment] 2023-05-09 08:20
I'm experiencing the same issue described above. Everything works well locally, but I get a timeout in Lambda.

Memory: 1536
Timeout: 300s

The website I'm scraping is `https://www.rad.cvm.gov.br/ENET/frmConsultaExternaCVM.aspx`

```
# package.json
"puppeteer-core": "^20.1.2"

# Lambda layer
chromium-v112.0.1-layer
```

My browser seems to be instantiated:

``` javascript
return await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(
        '/opt/nodejs/node_modules/@sparticuz/chromium/bin'
      ),
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
``` 

But it hangs when running `await browser.newPage()`, it has nothing to do with the actual page I want to crawl.

**Comment by rorykaletsch** [comment] 2023-07-06 09:53
Thank you @felipeclopes ! After many painstaking hours wanting to pull my hair out I got things working with this:

'UPDATE May 9th 3:35 PT:

I was able to get it working by:

Downgrading "@sparticuz/chromium" to "110.0.0"
Downgrading "puppeteer-core" to "19.6.3",
Updating lambda from ESM to CommonJS
Moving @sparticuz/chromium to dependencies instead of devDependencies'

I don't seem to have problems with **await browser.close()**, one thing I want to reiterate because I was getting **"Target(autoAttach)..."** errors is that browser launch looked like this, I had a small deviation in the form of slightly different args and it caused problems:

const browser = await puppeteer.launch({
        headless: chromium.headless,
        args: chromium.args,
        ignoreHTTPSErrors: true,
        executablePath: await chromium.executablePath(),
      });

**Comment by Sparticuz** [comment] 2023-07-21 19:34
Likely all you needed to do was install this package as a regular dependency, but not everyone is able to do that due to deployment restrictions. The .close() stuff seems to work fine if you disable the graphics stack.

Thanks for documenting what you did to fix it!

**Closed by Sparticuz** 2023-07-21 19:34 UTC
Labels: support

**Comment by shanmugavelan31** [comment] 2024-04-23 10:11
This is because of the min-configuration of the dependencies. I have change the dependencies from  "dependencies": {
    "@sparticuz/chromium": "^113.0.1",
    "dotenv": "^16.4.2",
    "puppeteer-core": "^20.1.2"
  } 
  to 
  "dependencies": {
    "@sparticuz/chromium": "^123.0.1",
    "dotenv": "^16.4.2",
    "puppeteer-core": "22.6.5"
  }
  now its working fine for me in AWS lambda .
  But in this configuration you can't find page.$x function in puppeteer-core. instead you can use it like the below code.
  
```
      const userNameXPath = '[id="signInFormUsername"]' //give Query selector path  
      const userName = await page.$$(userNameXPath) // instead of  $x use $$ 
      await userName[1].type('shan') 
```

**Comment by DynamicArray** [comment] 2024-05-01 13:33
This is still an issue for me.

Building:
{
  "dependencies": {
    "puppeteer-core": "22.6.5",
    "@sparticuz/chromium": "^123.0.1"
  }
}

This line hangs intermittently.

`const page = await browser.newPage();`

It happens when the Lambda is hot-loaded, I think (though not every time). Might that be a clue?

Browser launch is 
`	browser = await puppeteer.launch({
		defaultViewport: {
			width: viewWidth,
			height: viewHeight,
			deviceScaleFactor: batch[0].scale || 1,
		},
		ignoreHTTPSErrors: true,
		ignoreDefaultArgs: ['--enable-automation'],
		args: [
			...chromium.args,
			'--disable-infobars',
			'--no-sandbox',
			'--disable-setuid-sandbox',
			'--disable-gpu',
			'--enable-webgl',
			"--font-render-hinting=none",
			"--force-color-profile=srgb",

			'--single-process',
		],
		timeout: 10_000, 			// 10 seconds
		protocolTimeout: 10_000, 	// 10 seconds
		executablePath: await chromium.executablePath(),
		headless: chromium.headless,
	} );`
