### ISSUE TITLE
[BUG] CJK Fonts not working in chromium 122 / puppeteer-core 22.3 ?

### ISSUE THREAD

**Issue by rabbitfufu** [Sparticuz/chromium#236] opened 2024-03-04 16:24 UTC
## Environment

- `chromium` Version: 122.0.0
- `puppeteer` / `puppeteer-core` Version: 22.3.0
- Node.js Version: 20
- Lambda / GCF Runtime: Node 20 

I have use Sparticuz to generate pdfs that contain Asian characters.

I init like so:

```
await chromium.font(process.env.font_cjk)
await puppeteer.launch({
	args: chromium.args,
	defaultViewport: chromium.defaultViewport,
	executablePath: await chromium.executablePath(),
	headless: chromium.headless
})
```

Previously in Node 18 I was using:

	"@sparticuz/chromium": "^118.0.0"
	"puppeteer-core": "^21.4.0"

And this worked perfectly.  

However, after upgrading to Node 20 and:

	"@sparticuz/chromium": "^122.0.0"
	"puppeteer-core": "^22.3.0"

Asian fonts no longer work, and are blank, even though the call to chromium.font appears to work as expected, and no errors are thrown.  

Reverting back to Node 18 and the previous packages fixes this issue.

Have there been any changes to how I should be loading / using fonts?

Thanks for this great library and for your help.

**Comment by Sparticuz** [comment] 2024-04-03 17:23
dupe of #92

**Closed by Sparticuz** 2024-04-03 17:23 UTC
Labels: bug
