### ISSUE TITLE
[BUG] No longer working in Lambda

### ISSUE THREAD

**Issue by fire015** [Sparticuz/chromium#271] opened 2024-04-30 12:41 UTC
package.json:
```
    "@sparticuz/chromium": "123.0.1",
    "puppeteer-core": "22.6.4"
```

code:
```
  chromium.setGraphicsMode = false;

  console.log("## Launching browser");
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });

  console.log("## Creating new page");
  const page = await browser.newPage();

  console.log("## Setting user agent");
  await page.setUserAgent("Lambda PDF");

  console.log("## Going to " + url);
  await page.goto(url, {
    waitUntil: ["domcontentloaded", "networkidle0"],
  });
```

It's freezing after "Creating new page" appears in the console logs.

Lambda 18.x (tried with 20.x too) with 2GB memory
Runtime version ARN: `arn:aws:lambda:eu-west-2::runtime:b475b23763329123d9e6f79f51886d0e1054f727f5b90ec945fcb2a3ec09afdd`

**Comment by fire015** [comment] 2024-04-30 13:13
Downgrading to:

```
    "@sparticuz/chromium": "122.0.0",
    "puppeteer-core": "22.5.0"
```

Seems to have worked. Leaving this open just to verify I didnt make a mistake selecting the wrong package versions?

**Comment by leepa** [comment] 2024-04-30 15:24
This issue hit us today but we've not updated for a while so it seems to effect old versions too.

**Comment by Sparticuz** [comment] 2024-04-30 16:03
Make sure to leave graphics mode enabled. The option will be fixed in the next version. I've been traveling so I haven't had time to update to chromium 124.

**Comment by Sparticuz** [comment] 2024-04-30 16:04
> This issue hit us today but we've not updated for a while so it seems to effect old versions too. Is there anyway to make this project dump a stacktrace when the browser crashes?
> 

You can add puppeteer launch({dumpio:true}) in the object.

**Comment by urvik-bhalala** [comment] 2024-04-30 17:21
> > This issue hit us today but we've not updated for a while so it seems to effect old versions too. Is there anyway to make this project dump a stacktrace when the browser crashes?
> 
> You can add puppeteer.launch({dumpio:true}) in the object.

This isn't working as I have just added ({dumpio: true}) in launch method.

**Comment by shubhamvyapar** [comment] 2024-04-30 18:57
We have also started facing same issue. We have not update package version from 3 months. While trying to figure out the issue, we found that it is not working **only when html contains https URLs as we had some https URLs in img tag and link tag. On changing those URLs to http**, it starts working.

We had the following package.json
```
 "@sparticuz/chromium": "^109.0.5",
 "puppeteer-core": "^19.4.0",
```

Same thing is working fine after updating package version to (as mentioned by @fire015 )

```
"@sparticuz/chromium": "122.0.0",
"puppeteer-core": "22.5.0"
```

**Comment by ryan-concora** [comment] 2024-04-30 20:46
Having the same issue, not working in our production app.

**Comment by urvik-bhalala** [comment] 2024-04-30 21:25
> Downgrading to:
> 
> ```
>     "@sparticuz/chromium": "122.0.0",
>     "puppeteer-core": "22.5.0"
> ```
> 
> Seems to have worked. Leaving this open just to verify I didnt make a mistake selecting the wrong package versions?

Solved.

In my case, Downgrading to version as you describe and additionally I have to install "web-streams-polyfill" package. And added this line : global.ReadableStream = require('web-streams-polyfill').ReadableStream;

**Comment by leepa** [comment] 2024-04-30 21:40
We've worked around it by rolling back to the previous Lambda Runtime ARN.

**Comment by ryan-concora** [comment] 2024-04-30 22:19
> We've worked around it by rolling back to the previous Lambda Runtime ARN.

How do you do this with Serverless framework?

**Comment by iLykaPaul** [comment] 2024-04-30 22:19
We also ran into this today, the version changes suggested above:

`"@sparticuz/chromium": "122.0.0",
    "puppeteer-core": "22.5.0"`

and in our case an upgrade of the Chromium Lambda Layer to latest was the change combination that got us back up and running.

**Comment by ryan-concora** [comment] 2024-04-30 22:20
Ours doesn't seem to want to pull from s3 

`"An `executablePath` or `channel` must be specified for `puppeteer-core`"
name:"Error"
stacktrace:"at assert (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
at ChromeLauncher.computeLaunchArguments (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:102:36)
at async ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:70:28)
at async CoverPageGenerator.generatePDF (/var/task/src/CoverPage.js:60:19)
at async _getCoverPage (/var/task/src/zip.js:72:10)
at async exports.createSubmittal (/var/task/src/zip.js:33:21)
at async Worker.work (/var/task/src/worker.js:25:27)
at async post (/var/task/src/handler.js:19:3)"
type:"ERROR_TYPE_UNCAUGHT"`

**Comment by xanharris** [comment] 2024-05-01 02:02
> > We've worked around it by rolling back to the previous Lambda Runtime ARN.
> 
> How do you do this with Serverless framework?

Specify the run time management at the "provider" or "function" level in your `serverless.yml` file:
```yaml
functions:
  hello:
    runtimeManagement:
      mode: manual
      arn: arn:aws:lambda:us-east-1::runtime:0cdcfbdefbc5e7d3343f73c2e2dd3cba17d61dea0686b404502a0c9ce83931b9
```

The ARN version in the example above works for me (The offending ARN is mentioned in OP: https://github.com/Sparticuz/chromium/issues/271#issue-2271372222)

**Comment by gaurav112** [comment] 2024-05-01 08:33
Facing the same issue. 

Error: spawn Unknown system error -8

```
"@sparticuz/chromium": "^110.0.0",
"puppeteer": "19.6.0"
```


```
const browser = await puppeteer.launch({
    dumpio: true,
    args: chromium.args,
    executablePath: await chromium.executablePath(),
    headless: true,
    ignoreHTTPSErrors: true,
})
```

Tried upgrading to 

> Downgrading to:
> 
> ```
>     "@sparticuz/chromium": "122.0.0",
>     "puppeteer-core": "22.5.0"
> ```
> 
> Seems to have worked. Leaving this open just to verify I didnt make a mistake selecting the wrong package versions?

This still did not work. Any other ideas ??

**Comment by ryan-concora** [comment] 2024-05-01 08:44
> Facing the same issue.
> 
> Error: spawn Unknown system error -8
> 
> ```
> "@sparticuz/chromium": "^110.0.0",
> "puppeteer": "19.6.0"
> ```
> 
> ```
> const browser = await puppeteer.launch({
>     dumpio: true,
>     args: chromium.args,
>     executablePath: await chromium.executablePath(),
>     headless: true,
>     ignoreHTTPSErrors: true,
> })
> ```
> 
> Tried upgrading to
> 
> > Downgrading to:
> > ```
> >     "@sparticuz/chromium": "122.0.0",
> >     "puppeteer-core": "22.5.0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems to have worked. Leaving this open just to verify I didnt make a mistake selecting the wrong package versions?
> 
> This still did not work. Any other ideas ??


Our solution: 
- Added lambda layer, pulling from s3 doesn't seem to be working 
- Used this as executable path (examples need updating chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin';
- Removed   "@sparticuz/chromium-min": "122.0.0"
- Added as dev dep "@sparticuz/chromium": "122.0.0"
- "puppeteer-core": "22.5.0"
- Used v122.0.0 lambda layer

**Comment by LinusU** [comment] 2024-05-01 08:59
Removing our disabling of the graphics mode solved this for us:

```diff
- chromium.setGraphicsMode = false
+ // FIXME: re-enable in Chromium 124
+ // ref: https://github.com/Sparticuz/chromium/issues/271#issuecomment-2085784736
+ // chromium.setGraphicsMode = false
```

**Comment by 2803media** [comment] 2024-05-01 14:08
> > We've worked around it by rolling back to the previous Lambda Runtime ARN.
> 
> How do you do this with Serverless framework?

change this in the Runtime management configuration:

![Screenshot 2024-05-01 at 16 07 42](https://github.com/Sparticuz/chromium/assets/642545/bbcbd03c-96a2-4d0b-94e0-9d6be0ae035f)

**Comment by JakeDluhy** [comment] 2024-05-01 15:59
FWIW I was able to get it working with:
```
"@sparticuz/chromium": "122.0.0",
"puppeteer-core": "^21.1.1",
"puppeteer-extra": "^3.3.6",
"puppeteer-extra-plugin-stealth": "^2.11.2",
```

**Comment by adefemi** [comment] 2024-05-01 16:36
setting this works
```chromium.setGraphicsMode = true;```

**Comment by AkbarHabeeb** [comment] 2024-05-01 17:35
1. @Sparticuz Little curious to understand why the below version of packages are getting into an error when the latest package version was released? What is the breaking change we have?
`
"@sparticuz/chromium": "^106.0.2"
"puppeteer-core": "^18.0.5"
`
2. @shubhamvyapar For the suggested downgrade version "@sparticuz/chromium": "122.0.0", "puppeteer-core": "22.5.0", looks like we need Node 18, Can you kindly suggest any compatible version for Node 16 runtime env?

We got into an error saying _Navigation failed because browser has disconnected!_ seems like chrome crashed. Is this the same issue?

**Comment by jmartinezgdev** [comment] 2024-05-01 22:26
> setting this works `chromium.setGraphicsMode = true;`

This worked also for me 
chromium.setGraphicsMode = true;

puppeteer-core 22.6.0
@sparticuz/chromium 123.0.1,

**Comment by casyalex** [comment] 2024-05-02 08:19
I am curious about the root cause, seems it relate to SSL lib update, but why GraphicsMode can make it solved.

**Comment by vishwassingh47** [comment] 2024-05-02 08:37
> AkbarHabeeb

Yes we were getting the same error "Navigation failed because browser has disconnected!", but it was happening in those cases only where were are loading some asset using `https`, http and setOfflineMode(true) works fine.

**Comment by vishwassingh47** [comment] 2024-05-02 08:40
> We got into an error saying _Navigation failed because browser has disconnected!_ seems like chrome crashed. Is this the same issue?


Yes we were getting the same error "Navigation failed because browser has disconnected!", but it was happening in those cases only where were are loading some asset using https, http and setOfflineMode(true) works fine.

**Comment by gaurav112** [comment] 2024-05-02 08:51
This works for us.

We migrated to a previous version of Runtime on lambda(Node.Js 18.*)
```
ARN: arn:aws:lambda:ap-south-1::runtime:0cdcfbdefbc5e7d3343f73c2e2dd3cba17d61dea0686b404502a0c9ce83931b9
```

package.json for compatibility. 

```
"@sparticuz/chromium": "^119.0.0",
"puppeteer": "^21.5.2"
```

**Comment by bjoepfeiffer** [comment] 2024-05-02 16:15
I am having a similar issue to some of the more recently posted comments in this thread:

```
Navigation failed because browser has disconnected...
```

Others are saying that downgrading versions helped them, but I am starting to wonder if there is something else at play here.  This has crept up for many of us on all different versions.

Is there a corrupted browser object being cached between lambda executions and deploys?

Is it the downgraded version or the deploy of the downgraded version that is actually fixing the issue? I am wondering if this issue creeps back up for those who have said it has been fixed with a version downgrade.  

We started seeing this with these versions, which were previously working for a year. Then all of a sudden we started getting the error.

```
"@sparticuz/chromium": "114.0.0",
"puppeteer-core": "20.7.3"
```

Did AWS change something with lambdas and lambda layers that is biting all of us?

**Comment by Sparticuz** [comment] 2024-05-02 16:19
> 
> Did AWS change something with lambdas and lambda layers that is biting all of us?

Yes, AWS updated some libraries that are causing issues with the libraries included in this package. I'm in contact with the team at AWS and we will be working on a solution.

I would recommend pinning the lambda execution environment while this issue gets sorted.

**Comment by tomasalvarez13** [comment] 2024-05-02 16:19
I'm having a similar issue; it suddenly stopped working and started giving us this error code:

`The input directory "/opt/nodejs/node_modules/@sparticuz/chromium/bin/" does not exist.
`
I've tried all the solutions mentioned above, but none of them worked.

**Comment by tomasalvarez13** [comment] 2024-05-02 16:58
I rolled back manualy the runtime version and it worked

**Comment by raducretu** [comment] 2024-05-02 17:05
on one of my projects it works, on a different one, same settings same packages it does not work

**Comment by tyanko1** [comment] 2024-05-02 17:24
@tomasalvarez13 which runtime version worked for you, specifically?

**Comment by tomasalvarez13** [comment] 2024-05-02 17:26
@tyanko1 one from 27/04/2024

**Comment by LinusU** [comment] 2024-05-03 08:38
@raducretu you can specify the exact version of the runtime under something called "runtime management configuration". If you look at your logs from when things worked (a few days ago) you should see which arn they are using as it's printed in the INIT_START. Look for your old arn that worked, and then go in and change it to that for your Lambda.

More info here: https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html

**Comment by bjoepfeiffer** [comment] 2024-05-03 12:25
We were running our pdf export lambdas on `nodejs18.x`. Upgrading to `nodejs20.x` fixed this issue for now.

**Comment by LinusU** [comment] 2024-05-03 13:03
@fernedingd what is the reasoning behind using `await Promise.race([browser.close(), browser.close(), browser.close()])` instead of just `await browser.close()`? 🤔

**Comment by fernedingd** [comment] 2024-05-03 13:20
@LinusU we initially removed the `await browser.close()` call because it wasn't working reliably and the funktion worked without it. Calling `close` multiple times was a [suggestion from the FAQs](https://github.com/Sparticuz/chromium/issues/271). A single call should be enough, but I didn't want to risk having those issues again during peak production workloads over the weekend

**Comment by RubensMalaguteO7S** [comment] 2024-05-05 01:20
We were running our lambda on `nodejs16.x` and it couldn't be changed for internal reasons. The solution found was to revert the lambda runtime to a version from before the problem and update `chromium` and `puppeteer-core` versions to:

`"@sparticuz/chromium": "122.0.0"`
`"puppeteer-core": "17.1.3"`

**Comment by solancer** [comment] 2024-05-07 13:27
> This works for us.
> 
> We migrated to a previous version of Runtime on lambda(Node.Js 18.*)
> 
> ```
> ARN: arn:aws:lambda:ap-south-1::runtime:0cdcfbdefbc5e7d3343f73c2e2dd3cba17d61dea0686b404502a0c9ce83931b9
> ```
> 
> package.json for compatibility.
> 
> ```
> "@sparticuz/chromium": "^119.0.0",
> "puppeteer": "^21.5.2"
> ```

This worked, thankyou

**Comment by hasan-wajahat** [comment] 2024-05-08 20:57
👀

**Comment by alejandro-gstack** [comment] 2024-05-08 21:41
> @raducretu you can specify the exact version of the runtime under something called "runtime management configuration". If you look at your logs from when things worked (a few days ago) you should see which arn they are using as it's printed in the INIT_START. Look for your old arn that worked, and then go in and change it to that for your Lambda.
> 
> More info here: https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html

This worked for us! Lambdas are up and running after a couple of days of 🔥... But waiting for a definitive solution.

**Comment by davidhongpulsifi** [comment] 2024-05-09 12:04
INIT_START Runtime Version: nodejs:18.v24	Runtime Version ARN: arn:aws:lambda:eu-central-1::runtime:c09960ad0af4321e1a7cf013174f7c0d7169bf09af823ca2ad2f93c72ade708a

INIT_START Runtime Version: nodejs:18.v24	Runtime Version ARN: arn:aws:lambda:ap-southeast-1::runtime:c09960ad0af4321e1a7cf013174f7c0d7169bf09af823ca2ad2f93c72ade708a


Working with runtime above

**Comment by vince0946** [comment] 2024-05-10 02:19
> > We've worked around it by rolling back to the previous Lambda Runtime ARN.
> 
> How do you do this with Serverless framework?

serverless: maybe need version 3.x+, https://www.serverless.com/framework/docs-providers-aws-guide-functions
aws cli: https://docs.aws.amazon.com/cli/latest/reference/lambda/put-runtime-management-config.html
You should use lambda runtime management config, and find the old lambda arn in previous log which you could success running. "Runtime Version ARN: xxxx"

**Comment by davidhongpulsifi** [comment] 2024-05-10 02:23
> > > We've worked around it by rolling back to the previous Lambda Runtime ARN.
> > 
> > 
> > How do you do this with Serverless framework?
> 
> serverless: maybe need version 3.x+ since it is a new feature last year, https://www.serverless.com/framework/docs-providers-aws-guide-functions aws cli: https://docs.aws.amazon.com/cli/latest/reference/lambda/put-runtime-management-config.html You should use lambda runtime management config, and find the old lambda arn in previous log which you could success running. "Runtime Version ARN: xxxx"

```

import { custom } from './custom';
import { functions } from './functions';
import { plugins } from './plugins';
import { stepFunctions } from './step-functions';

export const main = {
    service: 'talent-management-report-fn',
    frameworkVersion: '3',
    useDotenv: true,
    configValidationMode: 'error',
    package: {
        individually: true,
    },
    provider: {
        name: 'aws',
        runtime: 'nodejs18.x',
        runtimeManagement: {
            mode: 'manual',
            arn: 'arn:aws:lambda:${opt:region}::runtime:${ssm:/configs/LAMBDA_NODEJS18_RUNTIME_ARN}',
        },
```
how we do now is store the ARN into SSM then map to runtimemanagement > arn

**Comment by denlukia** [comment] 2024-05-19 00:57
To everyone who's reading this thread looking for answers for Vercel, what eventually worked for me:

(I'm not sure what here is responsible for a fix) 
1. Set engine in project settings to 20.x
2. Switched from pnpm to npm
3. Updated @sparticuz/chromium-min to newest (123.0.1 as of writing) 
4. Updated chromium tar link also to newest (chromium-v123.0.1-pack.tar as of writing)

Just in case: puppeteer-core is "^21.3.8"

**Comment by krewetka** [comment] 2024-06-11 07:27
> Yes, AWS updated some libraries that are causing issues with the libraries included in this package. I'm in contact with the team at AWS and we will be working on a solution.
> 
> I would recommend pinning the lambda execution environment while this issue gets sorted.

@Sparticuz any news on this? Pinning to older version for a long run is not perfect solution for security reasons.

**Comment by glavenusio** [comment] 2024-06-26 13:44
version 123.0.1 seems to be working again on my end. not sure what's the root cause is.
I have tested generating more than 100 PDFs and it works properly.

lib version:
https://github.com/Sparticuz/chromium/releases/tag/v123.0.1

package.json
```
"@sparticuz/chromium": "123.0.1"
"puppeteer-core": "22.7.1"
```

code:
```
import puppeteer, { Browser } from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

const browser = await puppeteer.launch({
  args: [...chromium.args, '--disable-gpu'],
  defaultViewport: chromium.defaultViewport,
  executablePath: await chromium.executablePath(
    '/opt/nodejs/node_modules/@sparticuz/chromium/bin'
  ),
  headless: chromium.headless,
});

const page = await browser.newPage(); // <-- was causing lambda timeout 3 weeks ago


const signedUrl = await getSignedUrl(s3, new GetObjectCommand({
    Bucket: props.bucket,
    Key: props.htmlFilename,
  }));

await page.goto(signedUrl, { waitUntil: 'networkidle0' });
await page.pdf({
    format: 'A4'
});
  
await page.close()
```

Lambda runtime
```
INIT_START Runtime Version: nodejs:18.v30	Runtime Version ARN: arn:aws:lambda:ap-southeast-2::runtime:f89c264158db39a1cfcbb5f9b3741413df1cfce4d550c9a475a67d923e19e2f4
```

**Comment by krewetka** [comment] 2024-07-05 09:27
I confim 

using

`"@sparticuz/chromium": "123.0.1"
"puppeteer-core": "22.7.1"
` 

Worked for us as well. We used it as newest lambda layer from https://github.com/shelfio/chrome-aws-lambda-layer

**Closed** 2024-07-16 15:17 UTC
Labels: bug
